version: "3.8"

services:
  api:
    build: .
    restart: always

  nginx:
    image: nginx:stable
    depends_on:
      - api
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    restart: on-failure

  redis:
    image: redis:latest
